-- BRILLARA hardening migration
-- Run this once in Supabase SQL Editor before deploying the hardened application.

begin;

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 600),
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Hash existing advisor passwords once. The hardened app verifies the hash only
-- through the function below and never sends the advisor table to the browser.
create extension if not exists pgcrypto with schema extensions;
alter table if exists public.advisors add column if not exists password_hash text;
update public.advisors
set password_hash = extensions.crypt(password, extensions.gen_salt('bf'))
where password_hash is null and password is not null;

create or replace function public.verify_advisor_credentials(p_code text, p_password text)
returns table (id text, code text, name text)
language sql
security definer
set search_path = public, extensions
as $$
  select a.id::text, a.code, a.name
  from public.advisors a
  where a.code = p_code
    and a.password_hash = extensions.crypt(p_password, a.password_hash)
  limit 1;
$$;

revoke all on function public.verify_advisor_credentials(text, text) from public, anon, authenticated;
grant execute on function public.verify_advisor_credentials(text, text) to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_announcements_updated_at on public.announcements;
create trigger set_announcements_updated_at
before update on public.announcements
for each row execute function public.set_updated_at();

-- The Next.js server now accesses these tables with the Supabase service role.
-- Remove any old browser-facing policies, then deny direct anon/authenticated access.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('tickets', 'advisors', 'site_settings', 'announcements')
  loop
    execute format('drop policy if exists %I on public.%I', policy_record.policyname, policy_record.tablename);
  end loop;
end;
$$;

alter table if exists public.tickets enable row level security;
alter table if exists public.advisors enable row level security;
alter table public.site_settings enable row level security;
alter table public.announcements enable row level security;

revoke all on table public.tickets from anon, authenticated;
revoke all on table public.advisors from anon, authenticated;
revoke all on table public.site_settings from anon, authenticated;
revoke all on table public.announcements from anon, authenticated;
revoke all on sequence public.announcements_id_seq from anon, authenticated;

commit;
